{* file to handle db changes in 4.7.beta9 during upgrade *}

{$html_header} = '<style>{literal} .date{ text-align: right; } {/literal} </style> <table class="row"> <tr> <td class="wrapper last"> <table class="twelve columns"> <tr> <td class="text-pad header"> <a href="sample/"><img width="150" height="52" src="https://civicrm.org/sites/default/files/civicrm/custom/images/civicrm-logo-transparent.png" alt="Logo"></a> </td> <td class="date text-pad header"> {$smarty.now|date_format} </td> <td class="expander"></td> </tr> </table> </td> </tr> </table>';

{$html_footer} = '<style>{literal} .footer{ padding-bottom: 10px !important; } {/literal} </style> <table class="row"> <tr> <td class="wrapper last"> <table class="twelve columns"> <tr> <td class="text-pad footer"> <p>This is an autogenerated message. <strong>Do not reply </strong>to this thread. </p> </td> </tr> </table> </td> </tr> </table>';

INSERT INTO civicrm_mailing_component (id, name, component_type, subject, body_html, body_text, is_default, is_active) VALUES
(NULL, "Transactional Header", "T_Header", "Header for Workflow emails", '{$html_header|escape:"quotes"}', "Default Header Text for the Workflow Emails", 1, 1),
(NULL, "Transactional Footer", "T_Footer", "Footer for Workflow emails", '{$html_footer|escape:"quotes"}', "Default Footer Text for the Workflow Emails", 1, 1);
